### ISSUE TITLE
I have a problem with the ExapleProgram.cs

### ISSUE THREAD

**Issue by zhoulingyun** [glitch100/BinanceDotNet#130]
## Issue Overview
A short description of the issue

#### Repro Steps
In my centain c#windowapplication,i create a Form and copy code  to it that t the code from ExampleProgram.cs。After Run,i found  some  code have error  
example :     // Get All Orders
                var allOrders = await client.GetAllOrders(allOrdersRequest);
error:    BinanceExchange.API.Models.Response.Error.BinanceBadRequestException:“Malformed requests are sent to the server. Please review the request object/string”

##### Other Information
my code:  try
            {
                 createOrder = await Program._mainClient.CreateOrder(new CreateOrderRequest()
                {
                     IcebergQuantity = 100,
                     Price = 1,
                     Quantity = 100m,
                     Side = OrderSide.Buy,
                     Symbol = "XLMBNB",
                     Type = OrderType.Limit,
                 });
            }
            catch (BinanceBadRequestException badRequestException)
            {
                tbxlog.Text += "\n" + badRequestException;
            }
            catch (BinanceServerException serverException)
            {
                tbxlog.Text += "\n" + serverException;
            }
            catch (BinanceTimeoutException timeoutException)
            {
                tbxlog.Text += "\n" + timeoutException;
            }
            catch (BinanceException unknownException)
            {
                tbxlog.Text += "\n" + unknownException;
            }

and the error:
BinanceExchange.API.Models.Response.Error.BinanceBadRequestException: Malformed requests are sent to the server. Please review the request object/string
   at BinanceExchange.API.APIProcessor.<HandleResponse>d__8`1.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
  at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BinanceExchange.API.APIProcessor.<ProcessPostRequest>d__13`1.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown ---
  at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BinanceExchange.API.Client.BinanceClient.<CreateOrder>d__22.MoveNext()
--- The end of the stack trace in the previous location where the exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at QuantitativeTradingRobot.Form1.<Test>d__19.MoveNext() position C:\Users\云爹\Desktop\币圈\QuantitativeTradingRobot\Form1.cs:line 532

**Comment by zhoulingyun** [comment]
hahah ,I resolved it .... my  price is too small
