### ISSUE TITLE
Intermittent issue with 

### ISSUE THREAD

**Issue by raderag** [glitch100/BinanceDotNet#168]
## Issue Overview
A short description of the issue
I get a malformed requests intermittently when I call  GetAccountInformation().

#### Package Version: ?.?.?
latest - 4.12.0

#### Repro Steps
Happens sometimes when I call GetAccountInformation();

The client is connected, the keys are the same.  Once it happens, it doesn't seem to work for a while; I was wondering if it could be an issue with rate limiting?

##### Other Information

Malformed requests are sent to the server. Please review the request object/string

   at BinanceExchange.API.APIProcessor.<HandleResponse>d__8`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BinanceExchange.API.APIProcessor.<ProcessGetRequest>d__11`1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at BinanceExchange.API.Client.BinanceClient.<GetAccountInformation>d__31.MoveNext()
   
   
   Its generated in this call:
   public Task<AccountInformationResponse> GetAccountInformation(int receiveWindow = -1);
   
   which calls 
   
        public async Task<T> ProcessGetRequest<T>(BinanceEndpointData endpoint, int receiveWindow = 5000) where T : class
        
		this line:
			message = await RequestClient.SignedGetRequest(endpoint.Uri, _apiKey, _secretKey, endpoint.Uri.Query, receiveWindow);
			
		The key and secret are correct.

**Comment by raderag** [comment]
The issue is really simple, if using the binance.us system, you need the binance.us endpoint.
