### ISSUE TITLE
WebSocket:  The requested security protocol is not supported.

### ISSUE THREAD

**Issue by Igorus7** [glitch100/BinanceDotNet#87]
## Issue Overview
After upgrade from v4.4.0 to v4.5.0 WebSockets do not work anymore

#### Steps:
` var manualBinanceWebSocket = new InstanceBinanceWebSocketClient(client);
 var socketId = manualBinanceWebSocket.ConnectToDepthWebSocket(symbol, b => TaskFunc(b, pairId)
 );`

##### Other Information
Every time a WebSocket is called, the error occurs:

06.05.2018 5:45:39|Fatal|WebSocket.Connect|WebSocketSharp.WebSocketException: **An error has occurred during a TLS handshake**. ---> System.NotSupportedException: **The requested security protocol is not supported.**
                            at System.Net.SecurityProtocol.ThrowOnNotAllowed(SslProtocols protocols, Boolean allowNone)
                            at System.Net.Security.SslStream.AuthenticateAsClient(String targetHost, X509CertificateCollection clientCertificates, SslProtocols enabledSslProtocols, Boolean checkCertificateRevocation)
                            at WebSocketSharp.WebSocket.setClientStream()
                            --- End of inner exception stack trace ---
                            at WebSocketSharp.WebSocket.setClientStream()
                            at WebSocketSharp.WebSocket.doHandshake()
                            at WebSocketSharp.WebSocket.connect()

**Comment by igorskyx86** [comment]
I've got same error.
Adding *.binance.com certificate to trusted manually does not help.

**Comment by N4rk0** [comment]
@jalvarezca 
This worked for me too.
